### PR TITLE
Update pmi2 plugin with latest changes

### PR DESCRIPTION
**Pull request by lipari**
Compared against the latest files under origin/slurm-15.08.  Pulled in
changes to make more consitent.  Some of these where purely consmetic
(e.g., white spaces), while others were valid bug fixes that were
recently committed.

Also, re-enabled the building of the PAM plugin

### CODE REVIEW

**Comment by adammoody** [comment]
The changes here all look ok to me.

**Comment by lipari** [comment]
@adammoody, go ahead and push the "merge" button to merge my changes to your branch.  @grondo wanted to review it before we merge into slurm-2.3.3.chaos.

**Comment by grondo** [comment]
Instead of disable/enable PAM plugin, perhaps @adammoody could just remove the commit that disabled PAM from his PR. This would clean up history and make it less confusing. 

It would be great if bug fixes to files could be individually committed as well, as this would let us easily track which upstream changes have already been pulled into the backport when we try to maintain it in the future. However, if that is a bit challenging it perhaps isn't worth it at this time.

**Comment by adammoody** [comment]
It's a top priority for me to work on this PMIX_Ring branch this week.  My plan is to reapply each of my original commits, but exclude the commit that disables PAM and provide better comments for those commits with vague messages.  @lipari, do you have a breakdown of the various commits in your commit that brought in the latest changes?  We should break those into separate changes if it's not too difficult..

**Comment by lipari** [comment]
@adammoody, I have "given" you on the CZ a tar of what I believe are all your changes against the head of https://github.com/chaos/slurm/tree/slurm-2.3.3.chaos.  If all of your proposed changes are there and if it compiles and runs, then you can break the changes into individual commits along the lines @grondo suggested above.

**Pull request merged**
